In [ ]:
#チーム：ツイッター廃人
#2701763７　27017691

In [7]:
import pprint
import scipy.linalg   # SciPy Linear Algebra Library

A = scipy.array([[0, 1, -2],[-3, 7 ,-3],[3, -5, 5]])
l, V = scipy.linalg.eig(A)
pprint.pprint(l)
pprint.pprint(V)
pprint.pprint(V[:,0]) # columnの取り出し方

array([1.+0.j, 9.+0.j, 2.+0.j])
array([[-9.04534034e-01,  2.29415734e-01, -7.07106781e-01],
       [-3.01511345e-01,  6.88247202e-01,  1.11022302e-16],
       [ 3.01511345e-01, -6.88247202e-01,  7.07106781e-01]])
array([-0.90453403, -0.30151134,  0.30151134])


In [8]:
from sympy import *
t = symbols('t')
A = Matrix([[0, 1, -2],[-3, 7 ,-3],[3, -5, 5]])
xxx = diag(t,t,t)
pprint(xxx)
eq1 = simplify((A-xxx).det())
pprint(eq1)
solve(eq1,t)

⎡t  0  0⎤
⎢       ⎥
⎢0  t  0⎥
⎢       ⎥
⎣0  0  t⎦
-t⋅(t - 7)⋅(t - 5) + 6⋅t + 18


[1, 2, 9]

In [9]:
from pprint import pprint
from numpy import array, zeros, diagflat, dot, transpose
from scipy.linalg import eig
A = array([[0,1,1,1,1,0,1],
           [1,0,0,0,0,0,0],
           [1,1,0,0,0,0,0],
           [0,1,1,0,1,0,0],
           [1,0,1,1,0,1,0],
           [1,0,0,0,1,0,0],
           [0,0,0,0,1,0,0]]) #隣接行列

diag = []
for i in range(0,7):
    tmp = 0.0
    for j in range(0,7):
        tmp += A[i,j]
    diag.append(1.0/tmp)

D = diagflat(diag)
tA = dot(transpose(A),D) #転置

x = array([1,0,0,0,0,0,0])
pprint(dot(tA,dot(tA,x)))  #遷移

l, V = eig(tA)
v0 = V[:,0] 
pprint(v0) #規格化

array([0.35      , 0.16666667, 0.11666667, 0.05      , 0.26666667,
       0.05      , 0.        ])
array([0.69945653+0.j, 0.38286042+0.j, 0.32395882+0.j, 0.24296911+0.j,
       0.41231122+0.j, 0.1030778 +0.j, 0.13989131+0.j])


In [10]:
import numpy as np
from pprint import pprint

np.set_printoptions(formatter={'float': '{: 0.3f}'.format}) 
#pprint(A)
pprint(D)
#pprint(transpose(A))
pprint(dot(transpose(A),D))
x = array([1,0,0,0,0,0,0])
#pprint(x)
#pprint(dot(tA,dot(tA,dot(tA,x))))
l, V = eig(tA)
v0 = V[:,0]
#pprint(v0)


array([[ 0.200,  0.000,  0.000,  0.000,  0.000,  0.000,  0.000],
       [ 0.000,  1.000,  0.000,  0.000,  0.000,  0.000,  0.000],
       [ 0.000,  0.000,  0.500,  0.000,  0.000,  0.000,  0.000],
       [ 0.000,  0.000,  0.000,  0.333,  0.000,  0.000,  0.000],
       [ 0.000,  0.000,  0.000,  0.000,  0.250,  0.000,  0.000],
       [ 0.000,  0.000,  0.000,  0.000,  0.000,  0.500,  0.000],
       [ 0.000,  0.000,  0.000,  0.000,  0.000,  0.000,  1.000]])
array([[ 0.000,  1.000,  0.500,  0.000,  0.250,  0.500,  0.000],
       [ 0.200,  0.000,  0.500,  0.333,  0.000,  0.000,  0.000],
       [ 0.200,  0.000,  0.000,  0.333,  0.250,  0.000,  0.000],
       [ 0.200,  0.000,  0.000,  0.000,  0.250,  0.000,  0.000],
       [ 0.200,  0.000,  0.000,  0.333,  0.000,  0.500,  1.000],
       [ 0.000,  0.000,  0.000,  0.000,  0.250,  0.000,  0.000],
       [ 0.200,  0.000,  0.000,  0.000,  0.000,  0.000,  0.000]])
